"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$fill$cmd_duration $time$line_break$character'

[time]
disabled = false
format = "[$time]($style)"
style = "fg:66"

[cmd_duration]
show_milliseconds = true
min_time = 100
format = "[$duration](fg:101) "

[fill]
symbol = " "

[aws]
disabled = true

[python]
format = "via [${symbol}$virtualenv]($style)"

[git_status]
style = "bold purple"

[git_metrics]
disabled = false